# t07 — mining rate math, edge cases, vectors, pool conservation (§39–§40)
import orbit.mining.rate as rate
import orbit.mining.rewards as rewards
import orbit.core.bigint as bi

let pass = {"n": 0}
let fail = {"n": 0}
proc check(name, cond):
    if cond:
        pass["n"] = pass["n"] + 1
    else:
        fail["n"] = fail["n"] + 1
        print("FAIL: " + name)

let SMAX = rate.S_MAX_UNITS

# factor boundaries (§40)
check("uf-below-target-full", rate.user_factor_scaled(5000) == 1000000)
check("uf-above-target-tapers", rate.user_factor_scaled(40000) == 250000)
check("sf-at-max", rate.supply_factor_scaled(SMAX) == 1000000)
check("td-zero-height", rate.time_decay_scaled(0, 100000) == 1000000)
check("td-half-life", rate.time_decay_scaled(100000, 100000) == 500000)
check("td-two-half-lives", rate.time_decay_scaled(200000, 100000) == 250000)
check("nb-no-score", rate.node_boost_scaled(0) == 1000000)
check("nb-capped-ten-percent", rate.node_boost_scaled(1000000) == 1100000)
# §12: NodeBoost = 1 + min(Score, 0.10) — any score >= 0.10 earns the full cap
check("nb-full-cap-from-0.6", rate.node_boost_scaled(600000) == 1100000)
check("nb-over-max-clamps-like-full", rate.node_boost_scaled(5000000) == 1100000)

# invalid inputs rejected deterministically (§40)
var threw = false
try:
    rate.supply_factor_scaled("99999999999999999999999")
catch e:
    threw = true
check("sf-over-max-rejected", threw)
threw = false
try:
    rate.user_factor_scaled(-5)
catch e:
    threw = true
check("negative-users-rejected", threw)

# reference vectors (§39) — golden file generated by tools/gen_mining_vectors
let vec_lines = []
import io as iomod
let raw = iomod.readfile("tests/vectors/mining_vectors.txt")
for line in split(raw, chr(10)):
    if len(line) > 8 and slice(line, 0, 7) == "vector_":
        push(vec_lines, line)

check("vector-file-count", len(vec_lines) == 4)
var all_vec_ok = true
for line in vec_lines:
    let parts = split(line, "|")
    let got_rate = rate.calculate_mining_rate(
        int(bi.bi_to_number(parts[1])), parts[2],
        int(bi.bi_to_number(parts[3])), int(bi.bi_to_number(parts[4])))
    if got_rate != parts[5]:
        all_vec_ok = false
        print("  vector mismatch:", parts[0], "got", got_rate, "want", parts[5])
    let got_reward = rewards.calculate_block_reward(
        got_rate, int(bi.bi_to_number("60")), parts[2])
    if got_reward != parts[6]:
        all_vec_ok = false
        print("  reward mismatch:", parts[0], "got", got_reward, "want", parts[6])
check("golden-vectors-match", all_vec_ok)

# reward conservation (§38): never exceeds remaining pool
# reward conservation against vector_1's rate/pool (462726000 from golden file)
check("reward-basic",
      rewards.calculate_block_reward("7712100", 60, "90000000000000000") == "462726000")
let r2 = rewards.calculate_block_reward("7380000", 60, "100000000")
check("reward-pool-pinned", r2 == "100000000")

print("t07 mining: " + str(pass["n"]) + " passed, " + str(fail["n"]) + " failed")
if fail["n"] > 0:
    raise "t07 FAILED"
